"""Initial CMMI schema

Revision ID: 4e5aec9f5fe2
Revises: 
Create Date: 2026-01-08 06:58:58.538438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5aec9f5fe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maturity_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_area_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generic_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('generic_goal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generic_goal_id'], ['generic_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('maturity_level_id', sa.Integer(), nullable=True),
    sa.Column('process_area_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maturity_level_id'], ['maturity_levels.id'], ),
    sa.ForeignKeyConstraint(['process_area_category_id'], ['process_area_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generic_practice_elaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gp_elaboration', sa.Text(), nullable=True),
    sa.Column('process_area_id', sa.Integer(), nullable=True),
    sa.Column('generic_practice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generic_practice_id'], ['generic_practices.id'], ),
    sa.ForeignKeyConstraint(['process_area_id'], ['process_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specific_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process_area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['process_area_id'], ['process_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specific_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specific_goal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specific_goal_id'], ['specific_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specific_practices')
    op.drop_table('specific_goals')
    op.drop_table('generic_practice_elaborations')
    op.drop_table('process_areas')
    op.drop_table('generic_practices')
    op.drop_table('process_area_categories')
    op.drop_table('maturity_levels')
    op.drop_table('generic_goals')
    # ### end Alembic commands ###
