#encoding: utf-8 
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

maturity_level = MaturityLevel.create([
	{ id: 1, name: '1: Initial',                description: 'Processes are usually ad hoc and chaotic. The organization usually does not provide a stable environment to support processes. Success in these organizations depends on the competence and heroics of the people in the organization and not on the use of proven processes. In spite of this chaos, maturity level 1 organizations often produce products and services that work, but they frequently exceed the budget and schedule documented in their plans. <br> Maturity level 1 organizations are characterized by a tendency to overcommit, abandon their processes in a time of crisis, and be unable to repeat their successes.'},
	{ id: 2, name: '2: Managed',                description: 'The projects have ensured that processes are planned and executed in accordance with policy; the projects employ skilled people who have adequate resources to produce controlled outputs; involve relevant stakeholders; are monitored, controlled, and reviewed; and are evaluated for adherence to their process descriptions. The process discipline reflected by maturity level 2 helps to ensure that existing practices are retained during times of stress. When these practices are in place, projects are performed and managed according to their documented plans. <br>  Also at maturity level 2, the status of the work products are visible to management at defined points (e.g., at major milestones, at the completion of major tasks). Commitments are established among relevant stakeholders and are revised as needed. Work products are appropriately controlled. The work products and services satisfy their specified process descriptions, standards, and procedures.'},
	{ id: 3, name: '3: Defined',                description: 'Processes are well characterized and understood, and are described in standards, procedures, tools, and methods. The organization’s set of standard processes, which is the basis for maturity level 3, is established and improved over time. These standard processes are used to establish consistency across the organization. Projects establish their defined processes by tailoring the organization’s set of standard processes according to tailoring guidelines. (See the definition of “organization’s set of standard processes” in the glossary.) <br> A critical distinction between maturity levels 2 and 3 is the scope of standards, process descriptions, and procedures. At maturity level 2, the standards, process descriptions, and procedures can be quite different in each specific instance of the process (e.g., on a particular project). At maturity level 3, the standards, process descriptions, and procedures for a project are tailored from the organization’s set of standard processes to suit a particular project or organizational unit and therefore are more consistent except for the differences allowed by the tailoring guidelines. <br> Another critical distinction is that at maturity level 3, processes are typically described more rigorously than at maturity level 2. A defined process clearly states the purpose, inputs, entry criteria, activities, roles, measures, verification steps, outputs, and exit criteria. At maturity level 3, processes are managed more proactively using an understanding of the interrelationships of process activities and detailed measures of the process, its work products, and its services. <br> At maturity level 3, the organization further improves its processes that are related to the maturity level 2 process areas. Generic practices associated with generic goal 3 that were not addressed at maturity level 2 are applied to achieve maturity level 3.'},
	{ id: 4, name: '4: Quantitatively Managed', description: 'The organization and projects establish quantitative objectives for quality and process performance and use them as criteria in managing projects. Quantitative objectives are based on the needs of the customer, end users, organization, and process implementers. Quality and process performance is understood in statistical terms and is managed throughout the life of projects. <br> For selected subprocesses, specific measures of process performance are collected and statistically analyzed. When selecting subprocesses for analyses, it is critical to understand the relationships between different subprocesses and their impact on achieving the objectives for quality and process performance. Such an approach helps to ensure that subprocess monitoring using statistical and other quantitative techniques is applied to where it has the most overall value to the business. Process performance baselines and models can be used to help set quality and process performance objectives that help achieve business objectives. <br> A critical distinction between maturity levels 3 and 4 is the predictability of process performance. At maturity level 4, the performance of projects and selected subprocesses is controlled using statistical and other quantitative techniques, and predictions are based, in part, on a statistical analysis of fine-grained process data.'},
	{ id: 5, name: '5: Optimizing',             description: 'An organization continually improves its processes based on a quantitative understanding of its business objectives and performance needs. The organization uses a quantitative approach to understand the variation inherent in the process and the causes of process outcomes. <br> Maturity level 5 focuses on continually improving process performance through incremental and innovative process and technological improvements. The organization’s quality and process performance objectives are established, continually revised to reflect changing business objectives and organizational performance, and used as criteria in managing process improvement. The effects of deployed process improvements are measured using statistical and other quantitative techniques and compared to quality and process performance objectives. The project’s defined processes, the organization’s set of standard processes, and supporting technology are targets of measurable improvement activities. <br> A critical distinction between maturity levels 4 and 5 is the focus on managing and improving organizational performance. At maturity level 4, the organization and projects focus on understanding and controlling performance at the subprocess level and using the results to manage projects. At maturity level 5, the organization is concerned with overall organizational performance using data collected from multiple projects. Analysis of the data identifies shortfalls or gaps in performance. These gaps are used to drive organizational process improvement that generates measureable improvement in performance.'}
	])

process_area_category = ProcessAreaCategory.create([
	{ id: 1, name: 'Support',            description: 'Support process areas cover the activities that support product development and maintenance. The Support process areas address processes that are used in the context of performing other processes. In general, the Support process areas address processes that are targeted toward the project and can address processes that apply more generally to the organization.'},
	{ id: 2, name: 'Engineering',        description: 'Engineering process areas cover the development and maintenance activities that are shared across engineering disciplines. The Engineering process areas were written using general engineering terminology so that any technical discipline involved in the product development process (e.g., software engineering, mechanical engineering) can use them for process improvement.'},
	{ id: 3, name: 'Project Management', description: 'The Basic Project Management process areas address the activities related to establishing and maintaining the project plan, establishing and maintaining commitments, monitoring progress against the plan, taking corrective action, and managing supplier agreements.'},
	{ id: 4, name: 'Process Management', description: 'The Basic Process Management process areas provide the organization with a capability to document and share best practices, organizational process assets, and learning across the organization.'}
	])

process_area = ProcessArea.create([ 
	{ id: 1,  name: 'Configuration Management (CM)',                maturity_level_id: 2, process_area_category_id: 1 },
	{ id: 2,  name: 'Measurement and Analysis (MA)',                maturity_level_id: 2, process_area_category_id: 1 },
	{ id: 3,  name: 'Project Monitoring and Control (PMC)',         maturity_level_id: 2, process_area_category_id: 3 },
	{ id: 4,  name: 'Project Planning (PP)',                        maturity_level_id: 2, process_area_category_id: 3 },
	{ id: 5,  name: 'Process and Product Quality Assurance (PPQA)', maturity_level_id: 2, process_area_category_id: 1 },
	{ id: 6,  name: 'Requirements Management (REQM)',               maturity_level_id: 2, process_area_category_id: 3 },
	{ id: 7,  name: 'Supplier Agreement Management (SAM)',          maturity_level_id: 2, process_area_category_id: 3 },
	{ id: 8,  name: 'Decision Analysis and Resolution (DAR)',       maturity_level_id: 3, process_area_category_id: 1 },
	{ id: 9,  name: 'Integrated Project Management (IPM)',          maturity_level_id: 3, process_area_category_id: 3 },
	{ id: 10, name: 'Organizational Process Definition (OPD)',      maturity_level_id: 3, process_area_category_id: 4 },
	{ id: 11, name: 'Organizational Process Focus (OPF)',           maturity_level_id: 3, process_area_category_id: 4 },
	{ id: 12, name: 'Organizational Training (OT)',                 maturity_level_id: 3, process_area_category_id: 4 },
	{ id: 13, name: 'Product Integration (PI)',                     maturity_level_id: 3, process_area_category_id: 2 },
	{ id: 14, name: 'Requirements Development (RD)',                maturity_level_id: 3, process_area_category_id: 2 },
	{ id: 15, name: 'Risk Management (RSKM)',                       maturity_level_id: 3, process_area_category_id: 3 },
	{ id: 16, name: 'Technical Solution (TS)',                      maturity_level_id: 3, process_area_category_id: 2 },
	{ id: 17, name: 'Validation (VAL)',                             maturity_level_id: 3, process_area_category_id: 2 },
	{ id: 18, name: 'Verification (VER)',                           maturity_level_id: 3, process_area_category_id: 2 },
	{ id: 19, name: 'Organizational Process Performance (OPP)',     maturity_level_id: 4, process_area_category_id: 4 },
	{ id: 20, name: 'Quantitative Project Management (QPM)',        maturity_level_id: 4, process_area_category_id: 3 },
	{ id: 21, name: 'Causal Analysis and Resolution  (CAR)',        maturity_level_id: 5, process_area_category_id: 1 },
	{ id: 22, name: 'Organizational Performance Management (OPM)',  maturity_level_id: 5, process_area_category_id: 4 }
	])
